[package]
name = "opvault"
version = "0.1.0"
authors = ["Carlos Martín Nieto <cmn@dwim.me>"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
openssl = "0.10"
byteorder = "1.1"
base64 = "0.10"
uuid = { version = "0.7", features = ["serde"] }
